spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

rabbit:
  twitterExchange: twitter-topic-exchange
  twitterQueue: twitter-queue
  routingKey: new_tweet.*

server:
  port: 9091